# Generated by Django 5.0.6 on 2024-12-13 08:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('blog_body', models.TextField()),
                ('blog_img', models.ImageField(blank=True, null=True, upload_to='blog_img/')),
                ('snippet', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, choices=[('fiction', 'Fiction'), ('non_fiction', 'Non Fiction'), ('adventure', 'Adventure'), ('kids', 'Kids'), ('technology', 'Technology'), ('others', 'Others')], default='others', max_length=50, null=True)),
                ('pages', models.CharField(blank=True, max_length=10, null=True)),
                ('year_published', models.CharField(blank=True, max_length=5, null=True)),
                ('book_type', models.CharField(blank=True, max_length=20, null=True)),
                ('book_cover', models.ImageField(upload_to='book_cover/')),
                ('snippet', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_time', models.TimeField(blank=True, null=True)),
                ('event_img', models.ImageField(blank=True, null=True, upload_to='event_img/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeaderSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=50, null=True)),
                ('button_one', models.CharField(blank=True, max_length=15, null=True)),
                ('button_two', models.CharField(blank=True, max_length=15, null=True)),
                ('banner_img', models.ImageField(upload_to='banner_img/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
